### ISSUE TITLE
序中有不通的地方

### ISSUE THREAD

**Issue by swdmike** [zealotCE/America-Against-America#10]
在序言中：
。。。。抽象推理要能够说服人，很重要的，**点是驾**有没有令人信服的事实奠基有时候人们需要做一种工作。。。。

**Comment by zealotCE** [comment]
markdown 中已修改，其他格式我同步一下。

**Comment by Refrain1125** [comment]
> markdown 中已修改，其他格式我同步一下。

这里“很重要的一点是”后面漏了一个“它”
