### ISSUE TITLE
Kolona的亚美尼亚人 疑为 Kalona的阿米什人（Amish）

### ISSUE THREAD

**Issue by zhangchunlin** [zealotCE/America-Against-America#11]
Kolona的亚美尼亚人，在网络上怎么都搜不到，搜拒绝现代化的，应该是Kalona的阿米什人（Amish）
亚美尼亚人并不拒绝现代化啊，不是刚和阿塞拜疆用现代化兵器打过几场吗？
如果王沪宁原文如此，这么严重的错误，应该加个编者注。
`
离开爱荷华市（Iowa City）不远，大约十几分钟的汽车行程，就有一块亚美尼亚人的居住区，叫科罗那（Kolona）。带着上述问题，我来到这个地方。在快要进入科罗那时，就可以在公路上看到十七、十八世纪欧洲式样的马车，一匹马拖着一个小车厢，里面坐着一般穿着黑色服装的亚美尼亚人。这里的公路也有特别的设计，在汽车道两旁，划了马车道。因为亚美尼亚人不接受现代化的汽车，要坐马车。政府有关部门花了很多气力才说服他们，马车在公路上是非常危险的，要他们在马车后面，装一块醒目的红牌子，提醒开车的人注意。
`

**Comment by burid** [comment]
没错，那个外国人 John.M.Zielinski 写的书名应该叫做[《Amish Buggies Across America》](https://www.amazon.com/Amish-Buggies-Across-America-Zielinski/dp/0910381348/)
![封面](https://images-na.ssl-images-amazon.com/images/I/510bRfdIpAL._SX373_BO1,204,203,200_.jpg)

**Comment by heganyuliang** [comment]
刚写了篇关于这个的论文，这个描述完全是阿米什人，可能当年王沪宁不知道 Amish 怎么翻译吧

**Comment by asxpa** [comment]
我也读到这里了。综合谷歌和维基百科，此处应为Kalona, Iowa

**Comment by zealotCE** [comment]
嗯，我看了一下确实应该是王沪宁先生弄错了。已添加对应的注释。
