### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by imshawin** [zealotCE/America-Against-America#16]
望着满街写满中国字的**找**牌

**Comment by dragon-yuan** [comment]
一、不均匀的土地1.美国制造的疑惑CA985 经过日本东京，然后长途飞越波涛汹涌的太平洋，抵达旧金山。由于飞机误点，与欧洲抵美和日本抵美的班机挤在一起。平日里十分宽敞的取行李及过海关的大厅显得十分拥挤，人声鼎沸。不论从何处来的人，都带着一种抵达美国的兴奋心情。有一架飞机可能是从法国来的，许多人讲法语。排队过关，等了一个多小时，大家也**_象_**在中国一样发牢骚，等的时间太久。许多人都以为排队在西方应该是没有的，岂料一到美国就要排这么长时间的队。旧金山机场入境处的海关办理柜台分为三类：一是美国公民，二是非美国公民，三是新移民。左边前两个入口为美国公民的入口，人烟稀少，显出作为美国公民的优越。非美国公民，入关口人数最多，顿觉低人一等。

**Comment by dragon-yuan** [comment]
联合国大厦的建筑雄伟堂皇。我们去了安全理事会，拍了照。**有**前往联合国大会会场，找到中国代表团的席位，坐上去拍了一张照片。

**Comment by dragon-yuan** [comment]
商品化具有惊人的力量，它推使人们走向每一块有利可图的地方。最典型的像肯**塔**鸡、汉堡包、可口可乐、百事可乐、Crest 牙膏、万宝路香烟、联合邮包递运公司等，到处可见，哪怕是在非常偏僻的地方。

**Comment by raymondyan** [comment]
markdown -> line 25 col 28 -> 人类 ~~杜~~ 社 会

**Comment by chacha1024** [comment]
竞选有一个强大的机制，这就是选民的选票。如果得不到选民的选票，一切都无从谈起。只有得到了多数选民的选票，才能掌握大权，入主<del>**自**</del>白宫。受这种机制的吸引，大选中，候选人首先必须对公众关心的问题发表见解。其实两党之间没有什么意识形态的分歧，有的只是在同一意识形态下对基本政策和具体政策的分歧。可以说，它们之间的分歧在于对一些共同认同的问题持什么态度。

**Comment by zhu-zhiyun** [comment]
美国社会是最少神秘感的社会。人们在这个社会中长大，对任何事务均无什么神秘感。**~~送~~**这是美国文化中的一个不可分离的部分。

**Comment by zhu-zhiyun** [comment]
政治的非神秘化还表观**~~往~~**在新闻界的报道上，新闻界在政治报道方面十分活跃，如水门事件就是由新闻界搞出来的，伊朗门事件、国防部受贿案，都与记者有关。

**Comment by zhu-zhiyun** [comment]
在发达资本主义国家，例如美国，个人主义占主导**~~堆~~**地位，什么东西促进着人们的工作态度，很值得分析。
