### ISSUE TITLE
有没有更好的办法将这类优秀的旧书更多地数字化？

### ISSUE THREAD

**Issue by Colstuwjx** [zealotCE/America-Against-America#37]
首先，很感谢 @zealotCE  能够将这本书做成电子版并分享出来（尽管这仍然有版权的风险存在）。然后看到 README 里写的这本书是 OCR + 手工校对制作的。

想问下，有没有一个系统性的方法，把这类优秀的旧书通过技术的手段做成电子版，能够让更多人读到（前提是非盈利，或者和出版社合作的形式？）。
是否可以头脑风暴一下 😁

**Comment by zealotCE** [comment]
谷歌有出国一个方案，利用的是自动化的对书籍翻页并拍照，并图像处理后平铺出来合成PDF文件。但是问题是内容其实是图片，而不是文字。
如果是像现在这种转文字的话，OCR技术受限于识别率和多语言其实不太好弄。（拉丁语系还好，毕竟单词少）而且，有些旧书质量很差的就不太好控制。
简单说，我目前没有太好的办法，个人觉得还是只能靠爱发电。

**Comment by wacxr123** [comment]
有啊，Google原来的验证码图片都是美国一些图书馆里的片段，你在输入验证码的时候就帮着人家完成图书数字化的任务了（
