### ISSUE TITLE
基于 ZealotCE 的epub ，我修正出了一个新的epub

### ISSUE THREAD

**Issue by Refrain1125** [zealotCE/America-Against-America#39]
- 把第六章第 1 节“争夺白宫”中的两党候选人在“一些主要问题上的看法”整理成表格（实体书里也更像一份表格）； 
- 修正了几处错别字、引号误用（“单项否决“权）、半角标点误用（几处冒号、一处逗号）和全角标点误用（序里的People's Park）；
- 给正文中（大多数）“见‘第X章第 x 节’”添加了跳转链接；
- 出于个人习惯，给正文中的括号及其中内容作了缩小字体处理；
- 原本是 epub 3 ，现在是 epub 2。 

另外我主要在多看上看书，所以只适配了多看（主要是多看封面全屏和字体，另外就是表格，以多看对表格支持之垃圾程度，其他app应该不会出问题，没有弹注，所以其他部分也谈不上适配不适配的，在其他app应该不会有大的不同，当然我也不能完全保证）

下载链接：链接: https://pan.baidu.com/s/1bpriJYR8bMxM-zI5qSkcoQ 提取码: 3vgn

**Comment by Refrain1125** [comment]
表格在多看上的效果
[https://ftp.bmp.ovh/imgs/2021/04/71c484aef8bc8128.png](url)

**Comment by zealotCE** [comment]
可以提交上来我进行merge 
前段时间忙工作去了
